//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlquilerVehiculo_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int CodReserva { get; set; }
        public string CodVehiculo { get; set; }
        public string CodCliente { get; set; }
        public Nullable<System.DateTime> FechaReserva { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> NroDias { get; set; }
        public Nullable<int> NroRetraso { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
